export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const GET_COMMENTS = 'GET_COMMENTS'

export const INCREAMENT = 'INCREMAENT'
export const DECREAMENT = 'DECREAMENT'